# Site settings
baseurl = "https://yogawithgabs.netlify.com/"
title = "Yoga With Gabrielle"
paginate = 5
buildFuture = true

[[menu.social]]
  name = "Instagram"
  title = "fab fa-instagram"
  url = "https://www.instagram.com/yogawithgabrielle/"

[[menu.main]]
  name = "About"
  title = "About"
  url = "/about/"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"

[params]
  author = "Gabrielle Davies"
  twitter = "xaprb"
  classes = []

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
